# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FullyNoded2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FullyNoded2
  pod 'LibWally', :git => 'https://github.com/blockchain/LibWally-Swift.git', :branch => 'master', :submodules => true

  target 'FullyNoded2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FullyNoded2UITests' do
    # Pods for testing
  end

end
