# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'StandUp-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for StandUp-iOS

pod 'CoreBitcoin', :podspec => 'https://raw.github.com/oleganza/CoreBitcoin/master/CoreBitcoin.podspec'

  target 'StandUp-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

