#!/bin/zsh

# This script generates the full text of the `OutputFormats.md` file.
#
# $ ./create_output_formats.sh > OutputFormats.md

print_variants() {
    SCRIPT=$1
    ENVELOPE=`eval $1`
    LAYOUT=${2:-lr}

    # echo "## $TITLE\n"

    echo "### Envelope CLI Commands\n"
    echo '```bash'
    echo $SCRIPT
    echo '```'

    echo "\n### Envelope Notation\n"
    echo '```'
    envelope --envelope $ENVELOPE
    echo '```'

    echo "\n### Tree Format\n"
    echo '```'
    envelope --tree $ENVELOPE
    echo '```'

    echo "\n### Tree Format (\`hide-nodes\`)\n"
    echo '```'
    envelope --tree --hide-nodes $ENVELOPE
    echo '```'

    echo "\n### Mermaid\n"
    echo '```mermaid'
    envelope --mermaid --layout $LAYOUT $ENVELOPE
    echo '```'

    echo "\n### Mermaid (\`hide-nodes\`)\n"
    echo '```mermaid'
    envelope --mermaid --hide-nodes --layout $LAYOUT $ENVELOPE
    echo '```'
}

cat <<'EOF'
<!-- Do not modify this file directly! -->
<!-- It is generated by the `create_output_formats.sh` script. -->

# Output Formats

A comparison of the various Envelope output formats.

## Overview

These examples compare a series of Gordian Envelope output in its various formats:

* envelope notation
* tree format
* tree format (`hideNodes`)
* [Mermaid](https://mermaid-js.github.io/mermaid/#/) format
* Mermaid format (`hideNodes`)

The `hideNodes` versions are better for understanding an envelope's semantic content. While the regular versions are better for understanding the specific structure of an envelope, including locating all of its digests.

EOF

cat <<'EOF'

## Plaintext

* Leaf elements (elements having no children) have blue outlines.
* CBOR leaf elements (like strings, but they can be of any complexity) are represented by rectangles.
* The digests shown in each element are the first four bytes of the 32-byte digest associated with each element.
* Every element you see is *itself* an envelope that can be extracted and manipulated. If two digests match, the contents of the envelopes they represent also necessarily match.
* Since they omit the NODE digest points, the `hideNodes` variants don't show any digests for both simplicity and to avoid misleading.

EOF

print_variants 'envelope subject "Hello"'

cat <<'EOF'

## Signed Plaintext

* Internal elements (elements with children) are represented with red outlines.
* A `NODE` element appears when one or more assertions are present on a subject. They are represented by circles. They have one arm for the `subject` and an additional arm for each assertion.
* An `ASSERTION` element is represented by the Mermaid `stadium`  shape, and has exactly two arms: `predicate` and `object`.
* Well-known values like the `verifiedBy` are represented by trapezoids, and are encoded as short integers.
* In the `hideNodes` variants, assertions appear to stem from the subject of the envelope.

EOF

print_variants 'envelope subject "Hello" | \
    envelope sign --prvkeys `envelope generate prvkeys`'

cat <<'EOF'

## Encrypted Subject

* `ENCRYPTED`, `ELIDED`, and `COMPRESSED` elements appear with dotted outlines in the Mermaid output formats, to indicate that they may be replaced with their unencrypted/unelided/uncompressed counterparts without invalidating the digest tree.
* `ENCRYPTED` elements are represented by the Mermaid `asymmetric` shape.

EOF

print_variants 'envelope subject "Alice" | \
    envelope assertion "knows" "Bob" | \
    envelope encrypt --key `envelope generate key`'

cat <<'EOF'

## Top-Level Assertion

* As mentioned previously, all of the element types are themselves envelopes, and can therefore stand alone. In this case, we have extracted a single assertion.

EOF

print_variants 'envelope assertion create "knows" "Bob"'

cat <<'EOF'

## Elided Object

* `ELIDED` elements are represented by dotted hexagons.
* Note that the digest of the element "Bob" in the previous example matches the digest of the elided element above.
* Likewise, note that the digest of the subject "Alice" matches the encrypted version in the previous example.
* In fact, *all* the digests in this envelope match those in the previous example, indicating that the unencrypted/unelided form of this envelope has the exact same content.

EOF

print_variants 'ENVELOPE=`envelope subject "Alice" | envelope assertion "knows" "Bob"`; \
    TARGET=`envelope subject "Bob" | envelope digest`; \
    envelope elide removing $ENVELOPE $TARGET'

cat <<'EOF'

## Signed Subject

* A signature signs only the digest of the subject, in this case "Alice". So in this case, the "knows" assertions are not signed.
* Note that for every internal element, the children are displayed in the order that their digests are combined to form the parent's digest. In particular a `NODE`'s, `ASSERTION` elements are ordered by ascending digest value, so the order of the three assertion digests here: `4012caf2`, `78d666eb`, `c838acb5` reflects that ascending order.

EOF

print_variants 'envelope subject "Alice" | \
    envelope assertion "knows" "Bob" | \
    envelope assertion "knows" "Carol" | \
    envelope sign --prvkeys `envelope generate prvkeys`'

cat <<'EOF'

## Elided Assertions

* This is the same envelope from the previous example with its assertions elided. Note that the digests at every level still present are all the same.

EOF

print_variants 'SUBJECT=`envelope subject "Alice"`; \
ENVELOPE=`envelope assertion add "knows" "Bob" $SUBJECT | \
    envelope assertion "knows" "Carol" | \
    envelope sign --prvkeys \`envelope generate prvkeys\``; \
envelope elide revealing $ENVELOPE `envelope digest $ENVELOPE` `envelope digest $SUBJECT`'

cat <<'EOF'

## Wrapped Then Signed

* In this case the signature still only signs the subject, but the subject is an entire envelope that's been wrapped.
* `WRAPPED` elements are represented by trapezoids. They have exactly one arm, which is the root of the wrapped envelope.

EOF

print_variants 'envelope subject "Alice" | \
    envelope assertion add "knows" "Bob" | \
    envelope assertion "knows" "Carol" | \
    envelope subject --wrapped | \
    envelope sign --prvkeys `envelope generate prvkeys`'

cat <<'EOF'

## Encrypt to Recipients

* Top-to-bottom layout is also supported.

EOF

print_variants 'BOB_PUBKEYS="ur:crypto-pubkeys/lftaadfwhdcxndctnnflynethhhnwdkbhtehhdosmhgoclvefhjpehtaethkltsrmssnwfctfggdtaaddmhdcxtipdbagmoertsklaflfhfewsptrlmhjpdeemkbdyktmtfwnninfrbnmwonetwphehdprsepm"; \
CAROL_PUBKEYS="ur:crypto-pubkeys/lftaadfwhdcxeckpgwvyasletilffeeekbtyjlzeimmtkslkpadrtnnytontpyfyeocnecstktkttaaddmhdcxoyndtbndhspebgtewmgrgrgriygmvwckkkaysfzozclbgendfmhfjliorteenlbwzmfswzwk"; \
envelope subject "Hello" | envelope encrypt --recipient $BOB_PUBKEYS --recipient $CAROL_PUBKEYS' tb

cat <<'EOF'

## Complex Metadata

EOF

print_variants 'echo "ur:envelope/lrtpsptpcstpsfhdcxdstihtykswvlcmamsrcwdtgdwscmtyemfdcyprclhtjzsameimtdbedidspkmuvttpsptpsolftpsptpsgastpsptpcsiegagdfggutpsptpsolftpsptpcsiyiyjljpjnhsjytpsptpcsiefegdgofwtpsptpsolftpsptpcsiektjljpjetpsplttpsptpcstaadethdcxlbrhbkntmtrtlbesylhyolpswfmotsnedkctpsglrtrnclcxylspdkldjsckfmlatpsptpsolftpsptpcsieinjkidjttpsptpcsjnesemetdyeeeceheheseheheeeetpsptpsolftpsptpsgbdtpsplftpsptpcskpgshscxjpihidihjzinsrqdjtcxieihcxfpjyjzhsjktpsptpsolftpsptpsgbntpsptpcsidihjktpsptpsolftpsptpsgaotpsptpcsihjtjlkoihjztpsptpsolftpsptpcsiyhskpjyisjljptpsplstpsptpcstaadethdcxnsjykntoksoxspdsesdabeutidlpgockkiwkvwcmfldtoyqdhsmkvwjtadkoiysptpsptpsolftpsptpsgbdtpsptpcsisfpkkjtcxgmhsjtietpsptpsolftpsptpsgastpsptpcsjsgsinidjphsjpkkgwiyfxjljtiojpihjkjktpsptpsolftpsptpsgastpsptpcsjsgsinidjphsjpkkgwiyfxjljtiojpihjkjktpsptpsolftpsptpsgbdtpsplftpsptpcsjtfpjyjzhsjkcxguisjpkpioioihietpsptpsolftpsptpsgbntpsptpcsidihjtrksfcftp"'

cat <<'EOF'

## Verifiable Credential

EOF

print_variants 'echo "ur:envelope/lstpsptpsbmntpsptpcstaadethdcxfgkoiahtjthnissawsfhzcmyyldsutfzcttefpaxjtmobsbwimcaleykvsdtgajntpsptpsolftpsptpcsjsiaihjpjyiniyiniahsjyihglkpjnidihjptpsptpcsjeeheyeodpeeecendpemetestpsptpsolftpsptpcsjtihksjoinjphsjyinjljtfyhsjyihtpsptpcssecyjncscxaetpsptpsolftpsptpcsisjzhsjkjyglhsjnihtpsptpcsiogthsksktihjzjztpsptpsolftpsptpcsininjkjkkpihfyhsjyihtpsptpcssecyhybdvyaetpsptpsolftpsptpcsihjoisjljyjltpsptpcsksckghisinjkcxinjkcxgehsjnihjkcxgthsksktihjzjzdijkcxjoisjljyjldmtpsptpsolftpsptpcskscejojpjliyihjkjkinjljthsjzfyihkoihjzjljojnihjtjyfdjlkpjpjktpsptpcsbstpsptpsolftpsptpcsiniyinjpjkjyglhsjnihtpsptpcsihgehsjnihjktpsptpsolftpsptpcsiyjyjljoiniajktpsptpcslfingukpidimihiajycxehingukpidimihiajycxeytpsptpsolftpsptpcskscsiajljtjyinjtkpinjtiofeiekpiahsjyinjljtgojtinjyjktpsptpcsadtpsptpsolftpsptpsgaotpsptpcskscffxihjpjyiniyiniahsjyihcxjliycxfxjljnjojzihjyinjljttpsptpsolftpsptpcsiojkkpidimihiajytpsptpcskscegmfgcxhsjtiecxgtiniajpjlkthskoihcxfejtioinjtihihjpinjtiotpsptpsolftpsptpsgattpsptpcsksdkfekshsjnjojzihcxfejzihiajyjpiniahsjzcxfejtioinjtihihjpinjtiocxfwjlhsjpietpsptpsolftpsptpsgbttpsptpcsksdkfekshsjnjojzihcxfejzihiajyjpiniahsjzcxfejtioinjtihihjpinjtiocxfwjlhsjpietpsptpsolftpsptpsgaxtpsptpcstaadfzhdfzinglfpkbcyamyladcacnbzcmidwkjehezeispahnpliasbwkpfcwwzgwolrhguzoryntynbynepshljnfhbaghpfaaiyftfwhkdyknrhoelntlnnwmhloyssntskktuotpsptpsolftpsptpsgaatpsptpcsksdmguiniojtihiecxidkkcxfekshsjnjojzihcxfejzihiajyjpiniahsjzcxfejtioinjtihihjpinjtiocxfwjlhsjpietesfkbfd"'

cat <<'EOF'

## Warranty

This is the same credential above that has been elided, had additional assertions added, and then been signed by the employer.

EOF

print_variants 'echo "ur:envelope/lstpsptpsblstpsptpsblstpsptpsbmntpsptpcstaadethdcxfgkoiahtjthnissawsfhzcmyyldsutfzcttefpaxjtmobsbwimcaleykvsdtgajntpsptpsfhdcxctnewtmkmyparfrfkiclkihllrmsoxqdwylgkoimestectlurobzlrfhcsfdwlyntpsptpsolftpsptpcsjtihksjoinjphsjyinjljtfyhsjyihtpsptpcssecyjncscxaetpsptpsolftpsptpcsisjzhsjkjyglhsjnihtpsptpcsiogthsksktihjzjztpsptpsfhdcxgenddmgtcmvwmurpbblogwamdevteogujsghetwfeewndymhdygerfonnbbdmhsatpsptpsfhdcxgyjssbpefzurfztnwymwfxayosbesrgufeatzcosftonvwbanysnadesrlinsrprtpsptpsfhdcxghqdvyvdahrnldidkilehsrylnpmfxmkaxmorfhplsrtcsprjortteoejkdwpecxtpsptpsolftpsptpcsiniyinjpjkjyglhsjnihtpsptpcsihgehsjnihjktpsptpsfhdcxisldhlmnbklogopdathhspzsfxzmpkghamplmwzmrnhfwloeahttaelgnynlfxsptpsptpsfhdcxmnskwlbglaluaetbaoyafprohgnnpfmtpdrscpvdeshtssqzcnjsoscyltmodwcktpsptpsolftpsptpsgaotpsptpcskscffxihjpjyiniyiniahsjyihcxjliycxfxjljnjojzihjyinjljttpsptpsolftpsptpcsiojkkpidimihiajytpsptpcskscegmfgcxhsjtiecxgtiniajpjlkthskoihcxfejtioinjtihihjpinjtiotpsptpsfhdcxtbckaslrtsmhwyfttakkoyfhhnplytfsdlcawmtkcxayluspsklnaskgcffelnimtpsptpsolftpsptpsgbttpsptpcsksdkfekshsjnjojzihcxfejzihiajyjpiniahsjzcxfejtioinjtihihjpinjtiocxfwjlhsjpietpsptpsolftpsptpsgaxtpsptpcstaadfzhdfzinglfpkbcyamyladcacnbzcmidwkjehezeispahnpliasbwkpfcwwzgwolrhguzoryntynbynepshljnfhbaghpfaaiyftfwhkdyknrhoelntlnnwmhloyssntskktuotpsptpsolftpsptpsgaatpsptpcsksdmguiniojtihiecxidkkcxfekshsjnjojzihcxfejzihiajyjpiniahsjzcxfejtioinjtihihjpinjtiocxfwjlhsjpietpsptpsolftpsptpcsjsihjnjojzjlkkihihfdinjpihiefyhsjyihtpsptpcssecyhstknllatpsptpsolftpsptpcsjtihjnjojzjlkkihihgujyhsjykpjktpsptpcsiyhsiajyinkoihtpsptpsolftpsptpsgaxtpsptpcstaadfzhdfzlpcwldcxtanyierpionymdylkgmovodatnbgihzmisjtvwtiotwpwpmtdpfefxoektpmcategefpftlradlofpmkgaollgmdmsemgetnkomufwptguzmjzfhfmjettvdtpsptpsolftpsptpsgaatpsptpcskscsguiniojtihiecxidkkcxfejnjojzjlkkihjpcxfxjljpjodmhkndykws"'

cat <<'EOF'

## Compressed Warranty

This is the same warranty above, but with its subject compressed. Note that its signature is still valid.

EOF

print_variants 'WARRANTY="ur:envelope/lstpsptpsblstpsptpsblstpsptpsbmntpsptpcstaadethdcxfgkoiahtjthnissawsfhzcmyyldsutfzcttefpaxjtmobsbwimcaleykvsdtgajntpsptpsfhdcxctnewtmkmyparfrfkiclkihllrmsoxqdwylgkoimestectlurobzlrfhcsfdwlyntpsptpsolftpsptpcsjtihksjoinjphsjyinjljtfyhsjyihtpsptpcssecyjncscxaetpsptpsolftpsptpcsisjzhsjkjyglhsjnihtpsptpcsiogthsksktihjzjztpsptpsfhdcxgenddmgtcmvwmurpbblogwamdevteogujsghetwfeewndymhdygerfonnbbdmhsatpsptpsfhdcxgyjssbpefzurfztnwymwfxayosbesrgufeatzcosftonvwbanysnadesrlinsrprtpsptpsfhdcxghqdvyvdahrnldidkilehsrylnpmfxmkaxmorfhplsrtcsprjortteoejkdwpecxtpsptpsolftpsptpcsiniyinjpjkjyglhsjnihtpsptpcsihgehsjnihjktpsptpsfhdcxisldhlmnbklogopdathhspzsfxzmpkghamplmwzmrnhfwloeahttaelgnynlfxsptpsptpsfhdcxmnskwlbglaluaetbaoyafprohgnnpfmtpdrscpvdeshtssqzcnjsoscyltmodwcktpsptpsolftpsptpsgaotpsptpcskscffxihjpjyiniyiniahsjyihcxjliycxfxjljnjojzihjyinjljttpsptpsolftpsptpcsiojkkpidimihiajytpsptpcskscegmfgcxhsjtiecxgtiniajpjlkthskoihcxfejtioinjtihihjpinjtiotpsptpsfhdcxtbckaslrtsmhwyfttakkoyfhhnplytfsdlcawmtkcxayluspsklnaskgcffelnimtpsptpsolftpsptpsgbttpsptpcsksdkfekshsjnjojzihcxfejzihiajyjpiniahsjzcxfejtioinjtihihjpinjtiocxfwjlhsjpietpsptpsolftpsptpsgaxtpsptpcstaadfzhdfzinglfpkbcyamyladcacnbzcmidwkjehezeispahnpliasbwkpfcwwzgwolrhguzoryntynbynepshljnfhbaghpfaaiyftfwhkdyknrhoelntlnnwmhloyssntskktuotpsptpsolftpsptpsgaatpsptpcsksdmguiniojtihiecxidkkcxfekshsjnjojzihcxfejzihiajyjpiniahsjzcxfejtioinjtihihjpinjtiocxfwjlhsjpietpsptpsolftpsptpcsjsihjnjojzjlkkihihfdinjpihiefyhsjyihtpsptpcssecyhstknllatpsptpsolftpsptpcsjtihjnjojzjlkkihihgujyhsjykpjktpsptpcsiyhsiajyinkoihtpsptpsolftpsptpsgaxtpsptpcstaadfzhdfzlpcwldcxtanyierpionymdylkgmovodatnbgihzmisjtvwtiotwpwpmtdpfefxoektpmcategefpftlradlofpmkgaollgmdmsemgetnkomufwptguzmjzfhfmjettvdtpsptpsolftpsptpsgaatpsptpcskscsguiniojtihiecxidkkcxfejnjojzjlkkihjpcxfxjljpjodmhkndykws"; \
envelope compress --subject $WARRANTY'
